Platformer game
wolffles/game-iverse pull request #3
Opened 2019-05-07 06:10 UTC by Roodiger

A test platformer game

2019-05-07 17:46 UTC, wolffles commented
Awesome I appreciate the contribution. 

In the Interest of time, could you do me a favor and supply me  the `example2.js` script that's being required in index.html? I want to test it locally before I merge.

I think It would be a good idea for future contributors if we add a ReadMe file to the brickbreak and platformer folders with sample code for a basic working version.

2019-05-08 02:23 UTC, Roodiger commented
The example2.js file should be included there in the pull. You should be able to grab it there. 

Yeah that's a good call. I'll work on some sort of ReadMe if you don't get to it first

2019-05-08 03:05 UTC, wolffles commented
> The example2.js file should be included there in the pull. You should be able to grab it there.
I think it was ignored by the .gitignore file. I'm looking at the diff files and there isn't one

2019-05-08 03:09 UTC, Roodiger commented
@wolffles I'll look into it in a minute

2019-05-08 03:58 UTC, Roodiger commented
It should be there now? I made some slight changes. Sorry I'm getting used to GitHub. Let me know if you need anything.

2019-05-08 16:33 UTC, wolffles requested changes
There seems to be a misunderstanding of what this project is. I really like the enthusiasm in creating all  the code. this project should just be modules to export, the reason I asked for the JS file was to test to see if your code worked on my test repository. On my local system I have the game-iverse repo, and a separate test-repo which I `npm link` to the game-iverse repo and test if it works like an npm package.
the examples are just guidelines for a user to understand how it works.  I'll have to make a contribution file to explain this for future contributors

2019-05-08 16:33 UTC, wolffles commented on node_modules/game-iverse/brickbreak/brickbreakclasses.js
> +// }
@Roodiger why does your version have a `node modules/` folder with our package inside of it? This whole repo is the npm package and should not have our repo inside of it. Please remove it. 

The idea is to supply building blocks for others to use. I should have clarified that the html and js file you were supplying was for testing purposes only, and would be removed and added to a read me file upon merging. If you want to test your package create a test repo to `npm link` your two repos together.

2019-05-08 16:33 UTC, wolffles commented on node_modules/game-iverse/index.js
> +module.exports.platformer = platformerClasses;
`node_module/` remove

2019-05-08 16:33 UTC, wolffles commented on node_modules/game-iverse/package.json
> +}
`node_module/` remove

2019-05-08 16:33 UTC, wolffles commented on node_modules/game-iverse/platformer/levels.js
> +  global.GAME_LEVELS = GAME_LEVELS;
You should move this to the `platformer/READEME.md` and your test repository, I would like to try it out myself.
After I publish the new version we'll make a webpage to display our games. its just an NPM package shouldn't have a html doc to run. It should just be modules to be exported and imported. 

However in the npm package we shouldn't have a full game.

2019-05-08 16:33 UTC, wolffles commented on node_modules/game-iverse/platformer/platformer.html
> +</body>
Should place the `platformer/` folder in the root of the repo not in this `node_module/`

2019-05-08 16:33 UTC, wolffles commented on node_modules/game-iverse/platformer/platformer.js
> +}
I'm sorry you've done so much work, this is great just should be on our website advertising the package not in the package. We'll work on the site after.

2019-05-08 16:33 UTC, wolffles commented on package-lock.json
> +  }
please don't modify the package-lock file.

2019-05-08 16:33 UTC, wolffles commented on node_modules/game-iverse/platformer/style.css
> +}
belongs on the website.

2019-05-08 16:38 UTC, closed without merging